### ISSUE TITLE
Fix-dsig tool missing. Update docs

### ISSUE THREAD

**Issue by kateliev** [googlefonts/science-gothic#331]
@tphinney while doing build today this one popped up as a new kind of problem. It seems that G is no longer supporting the tool and the operation step is unneeded (?). See here for reference: https://github.com/googlefonts/gftools/issues/564 so the tool was missing in the latest gftools.

It is up for you to decide if that step should updated/removed from our [build documentation](https://github.com/googlefonts/science-gothic/blob/main/documentation/compiling_fonts.md). For now i am going to exclude that step from our build scripts and will add the table as dropped to the `sg-fix-unwanted-tables.py` tool.

In case you decide to keep the step, here is a hard-copy of the tool that we should add to our scripts folder:
https://github.com/googlefonts/gftools/blob/v0.8.8/bin/gftools-fix-dsig.py

**Comment by tphinney** [comment]
Aha, I did some checking because I couldn’t remember what the story was, and basically....

Microsoft Word used to treat OpenType fonts without a DSIG as second-class citizens and ignore their OpenType layout features (including kerning!). However, this behavior was halted in 2014.

So, ten years later, no need to create a dummy DSIG to get better behavior from Word.

I am updating the build documentation right now.  :)
